### ISSUE TITLE
Ardupilotmega MavCmd commands using CommandLong class

### ISSUE THREAD

**Issue by yaroslavkulinich** [urbanmatrix/mavlink-kotlin#48]
The question is how I can send ardupilotmega (or any other 3rd-party dialect) MavCmd command using the CommandLong message.
I see the CommandLong class accepts only MavCmd from the common package.

Or maybe I'm missing something? 

Thanks

**Comment by yaroslavkulinich** [comment]
Okay. I handled it.
The trick is to use MavEnumValue.from<xyz.urbanmatrix.mavlink.definitions.common.MavCmd>(xyz.urbanmatrix.mavlink.definitions.ardupilotmega.MavCmd.MAV_CMD_SCRIPTING.value)

**Comment by divyanshupundir** [comment]
Yes that's how we need to do it. I wanted to make it a bit better, but it is rarely used.

To make it a bit more clean you can use import alias of ApmCmd for Ardupilotmega commands.
