### ISSUE TITLE
Multiplatform definitions 

### ISSUE THREAD

**Issue by yaroslavkulinich** [urbanmatrix/mavlink-kotlin#53]
Consider to make definitions module (message and enum classes) as Kotlin Multiplatform module, even with one target (JVM).
It will make life of KMP developers much easier. Because currently I can't use this library in common sourceSet - I need to make expect-actual procedure for every message and field I'm going to use. It works, but from maintenance and further development perspective it's really time-consuming operation.

**Comment by divyanshupundir** [comment]
Hello @yaroslavkulinich.

Kotlin multi-platform has recently become stable. I had been waiting for this.

Please give me time till next weekend. I'm going to start the multi-platform setup and work in a few days.

**Comment by yaroslavkulinich** [comment]
@divyanshupundir thank you! Perfect news!

**Comment by divyanshupundir** [comment]
Hello @yaroslavkulinich, I have been trying to shift the codebase to multiplatform. I am currently working on the serialization module. You had told me about the Kmem library in this issue #33. Looks like they have made some changes in the project. I am unable to find the library. Can you please let me know how to get access to it, or some other library that could fit the usecase?

**Comment by yaroslavkulinich** [comment]
Hello @divyanshupundir.
It seems like they moved this functionality to foundation library.
Valid link with description here: https://docs.korge.org/memory/#

**Comment by divyanshupundir** [comment]
Thanks. For now, I am using simple ByteArray and bit manipulation for the data encoding and decoding for non-JVM targets. It is working for now. I will look into optimization and other libraries once I have mavlink-kotlin running on the different platforms.

**Comment by divyanshupundir** [comment]
BTW, I am working on the multiplatform migration [on this branch](https://github.com/divyanshupundir/mavlink-kotlin/tree/multiplatform). You can track the changes. Also, please let me know if you find a mistake, especially in the configuration.

**Comment by divyanshupundir** [comment]
@yaroslavkulinich, I have ported the library to multiplatform and version `1.2.0-alpha.5` should be available on maven in sometime.

I had to make several internal changes for this, but I've tried my best to keep the API changes to a minimum. Since it's a big migration, I will be testing the library for a few days before bumping it to stable.

Currently, the TCP and UDP connections are available only on JVM.

Contributions for adding the missing functionalities are welcome.

**Comment by yaroslavkulinich** [comment]
@divyanshupundir Thank you! You do a great job!
Message and Enum classes in common sourceSet would be enough to remove 90% of the headache.
Transport is not an issue.

**Comment by divyanshupundir** [comment]
Thanks a lot for the kind words!

Please do let me know if the serialization and deserialization of the messages are working fine. Currently, I have the means to test it only on Linux and JVM. If it works fine, I'll create a release this weekend or next week.

**Comment by yaroslavkulinich** [comment]
I was testing it for a few days and seems it works good.
Good job 👍

**Comment by divyanshupundir** [comment]
Awesome, I'll close this soon.

**Comment by divyanshupundir** [comment]
mavlink-kotlin v1.2.0 has been released with multiplatform support. Documentation will be update soon.
