### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Sm-Tv** [urbanmatrix/mavlink-kotlin#72]
private fun test() {
        job = CoroutineScope(Dispatchers.IO).launch {
            mavSDKServer = MavsdkServer()
            mavSDKPort = mavSDKServer.run("udp://:14550")
            drone = System("0.0.0.0", mavSDKPort)
        }
        binding.startSendMessage.setOnClickListener {
            val connection = UdpClientMavConnection("0.0.0.0", 14550, CommonDialect)

            try {
                val payload = RequestDataStream(targetSystem = 1u, targetComponent = 1u, startStop = 1u)
                connection.sendUnsignedV2(255u, 0u, payload)
            } catch (e: Exception) {
                println("exception = ${e}")
            }
        }
    }
    
    Good afternoon, please tell me, I'm new to mavlink. But I need to send a command to the drone so 
that it starts sending me telemetry. I decided to use your library and mavSDK. What am I doing wrong?
    When you click on the button, an error pops up that the connection is closed.
    java.io.IOException: The connection is closed

**Comment by divyanshupundir** [comment]
Hello @Sm-Tv,

There are two problems that I can see.

1. You should use `UdpServerMavConnection` and not `UdpClientMavConnection`.
3. You will not be able to use mavlink-kotlin alongside MAVSDK as there can be only one consumer. You may face unexpected problems with using both of them together connected to the same source.

**Comment by Sm-Tv** [comment]
Thanks a lot for the quick response. The message seems to be sent, but the drone does not respond to the command. What could be the problem, the system Id and compomemtId are specified correctly. Sorry to interrupt. But can I have a small example of sending a message?

My code:
private fun test() {
        CoroutineScope(Dispatchers.IO).launch {
            connection = UdpServerMavConnection(14550, CommonDialect)
            connection.connect()
        }
        binding.startSendMessage.setOnClickListener {
            val payload = RequestDataStream(targetSystem = 1u, targetComponent = 1u, reqStreamId = 0u, reqMessageRate = 1000u, startStop = 1u)
            CoroutineScope(Dispatchers.IO).launch {
                connection.sendUnsignedV2(1u, 1u, payload)
            }
        }
    }

**Comment by divyanshupundir** [comment]
You can do something like this for Ardupilot drones:

```kotlin
final override suspend fun requestDataStreams() {
    requestDataStream(MavDataStream.RAW_SENSORS, 2u)
    requestDataStream(MavDataStream.EXTENDED_STATUS, 2u)
    requestDataStream(MavDataStream.RC_CHANNELS, 2u)
    requestDataStream(MavDataStream.POSITION, 3u)
    requestDataStream(MavDataStream.EXTRA1, 10u)
    requestDataStream(MavDataStream.EXTRA2, 10u)
    requestDataStream(MavDataStream.EXTRA3, 3u)
}

private suspend fun requestDataStream(stream: MavDataStream, rate: UShort) {
    mavConnection.sendUnsignedV2(
        systemId = // Over here you need to specify your (GCS's) systemId
        componentId = // Same for componentId
        payload = RequestDataStream(
            targetSystem = 1u,
            targetComponent = 1u,
            startStop = 1u,
            reqStreamId = stream.value.toUByte(),
            reqMessageRate = rate
        )
    )
}
```

As for the `CoroutinesMavConnection`, I use it as a singleton (using Dagger/Hilt) in the applications. In your case, you can either use `viewModelScope` to connect it or `lifecycleScope` of the Activity.

Ideally, you should use a background service to connect the `CoroutinesMavConnection` and then use it in the different Activities/Services.

**Comment by Sm-Tv** [comment]
Thank you so much, you are the best

**Comment by divyanshupundir** [comment]
Thank you for the kind words. I will mark this issue as closed then.
